name: On Push

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  cd:
    if: github.event.repository.name != 'npm-package-template'
    needs:
      - ci
    uses: ./.github/workflows/cd.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
